//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAkademik.AkademikReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AkademikReference.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryModel(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertdata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertdata(string nim, string nama, string alamat, string email, int nilai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Display", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Display();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAkademik", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteAkademik(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbahAkademik", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UbahAkademik(string nim, string nama, string alamat, string email, int nilai);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ClientAkademik.AkademikReference.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ClientAkademik.AkademikReference.Service1Soap>, ClientAkademik.AkademikReference.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet QueryModel(string nim) {
            return base.Channel.QueryModel(nim);
        }
        
        public void insertdata(string nim, string nama, string alamat, string email, int nilai) {
            base.Channel.insertdata(nim, nama, alamat, email, nilai);
        }
        
        public System.Data.DataSet Display() {
            return base.Channel.Display();
        }
        
        public void DeleteAkademik(string nim) {
            base.Channel.DeleteAkademik(nim);
        }
        
        public void UbahAkademik(string nim, string nama, string alamat, string email, int nilai) {
            base.Channel.UbahAkademik(nim, nama, alamat, email, nilai);
        }
    }
}
